[package]
name = "monster_chess"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
flamegraph = "0.6.2"
shell-words = "1.1.0"
smallvec = "1.10.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "chess-perft"
harness = false
