[package]
name = "lotisa-bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
criterion = "0.4.0"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
rug = "1.19.1"
smallvec = "1.10.0"

[dev-dependencies]
criterion = "0.4.0"
